services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/salon
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
    command: npm run dev

  mongodb:
    ports:
      - '27017:27017'

  redis:
    ports:
      - '6379:6379'
