export const ErrorCodes = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',

  // Auth & OTP
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // RBAC
  ROLE_SLUG_EXISTS: 'ROLE_SLUG_EXISTS',
  ROLE_IN_USE: 'ROLE_IN_USE',

  // Cart & Catalog
  CART_ITEM_LIMIT: 'CART_ITEM_LIMIT',
  CART_BENEFIT_CONFLICT: 'CART_BENEFIT_CONFLICT',
  CART_MEMBERSHIP_REQUIRED: 'CART_MEMBERSHIP_REQUIRED',
  CART_INVALID_SELECTION: 'CART_INVALID_SELECTION',
  CART_NO_SELF_ITEMS: 'CART_NO_SELF_ITEMS',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  SERVICE_UNAVAILABLE_STATUS: 'SERVICE_UNAVAILABLE_STATUS',

  // Booking & Slots
  BOOKING_SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  BOOKING_CONCURRENCY_CONFLICT: 'BOOKING_CONCURRENCY_CONFLICT',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_INVALID_STATE: 'BOOKING_INVALID_STATE',

  // Payment & Wallet
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  RAZORPAY_ORDER_FAILED: 'RAZORPAY_ORDER_FAILED',
  RAZORPAY_INVALID_SIGNATURE: 'RAZORPAY_INVALID_SIGNATURE',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INSUFFICIENT_POINTS: 'WALLET_INSUFFICIENT_POINTS',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',
  IDEMPOTENCY_KEY_REPLAY: 'IDEMPOTENCY_KEY_REPLAY',
});
