export const WalletTransactionType = Object.freeze({
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT',
});

export const WalletTransactionCategory = Object.freeze({
  TOPUP: 'TOPUP',
  BOOKING_PAYMENT: 'BOOKING_PAYMENT',
  BOOKING_REFUND: 'BOOKING_REFUND',
  CASHBACK: 'CASHBACK',
  LOYALTY_POINTS_EARNED: 'LOYALTY_POINTS_EARNED',
  LOYALTY_POINTS_REDEEMED: 'LOYALTY_POINTS_REDEEMED',
  REFERRAL_BONUS: 'REFERRAL_BONUS',
  ADMIN_ADJUSTMENT: 'ADMIN_ADJUSTMENT',
  SUBSCRIPTION: 'SUBSCRIPTION',
});

export const WalletTransactionStatus = Object.freeze({
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
});
